#!/usr/bin/env php
<?php declare(strict_types=1);

if (isset($GLOBALS['_composer_autoload_path'])) {
    define('MODULES_COMPOSER_INSTALL', $GLOBALS['_composer_autoload_path']);

    unset($GLOBALS['_composer_autoload_path']);
} else {
    foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
        if (file_exists($file)) {
            define('MODULES_COMPOSER_INSTALL', $file);

            break;
        }
    }

    unset($file);
}

if (!defined('MODULES_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require MODULES_COMPOSER_INSTALL;

\PhpModules\Cli\Cli::create($argv)->run();
